name: Deploy to Vercel

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install pnpm
      run: npm install -g pnpm
      
    - name: Install Vercel CLI
      run: npm install -g vercel@latest
      
    - name: Build and Deploy
      run: |
        pnpm install
        pnpm run build
        vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
